<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Seeder;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // User::create([
        //     "name"          => "Admin",
        //     "nip"           => '8106323Z',
        //     "username"      => 'admin',
        //     "email"         => 'admin@gmail.com',
        //     "password"      => bcrypt('admin123'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "admin",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);
        // User::create([
        //     "name"          => "ALVIN",
        //     "nip"           => '9723003PRO',
        //     "username"      => '9723003PRO',
        //     "email"         => 'alvin@gmail.com',
        //     "password"      => bcrypt('alvin123'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "admin",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);
        // User::create([
        //     "name"          => "ARIEF SUKO",
        //     "nip"           => '8611098Z',
        //     "username"      => '8611098Z',
        //     "email"         => 'arief.suko@gmail.com',
        //     "password"      => bcrypt('8611098Z@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "admin",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);
        // User::create([
        //     "name"          => "ZULHENDRI",
        //     "nip"           => '7702003R2',
        //     "username"      => '7702003R2',
        //     "email"         => '7702003R2@gmail.com',
        //     "password"      => bcrypt('7702003R2@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);
        // User::create([
        //     "name"          => "PETRUS GADING AJI N.P",
        //     "nip"           => '8206390Z',
        //     "username"      => '8206390Z',
        //     "email"         => '8206390Z@gmail.com',
        //     "password"      => bcrypt('8206390Z@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);
        // User::create([
        //     "name"          => "SUPONO IMMANUEL",
        //     "nip"           => '7095008B',
        //     "username"      => '7095008B',
        //     "email"         => '7095008B@gmail.com',
        //     "password"      => bcrypt('7095008B@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);
        // User::create([
        //     "name"          => "JOKO NUR ASTANTO",
        //     "nip"           => '7907021Z',
        //     "username"      => '7907021Z',
        //     "email"         => '7907021Z@gmail.com',
        //     "password"      => bcrypt('7907021Z@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);
        // User::create([
        //     "name"          => "DINA SHOFWATI",
        //     "nip"           => '7902002D',
        //     "username"      => '7902002D',
        //     "email"         => '7902002D@gmail.com',
        //     "password"      => bcrypt('7902002D@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);
        // User::create([
        //     "name"          => "FAJRI SE",
        //     "nip"           => '7802008R',
        //     "username"      => '7802008R',
        //     "email"         => '7802008R@gmail.com',
        //     "password"      => bcrypt('7802008R@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);
        // User::create([
        //     "name"          => "RONI KARUA",
        //     "nip"           => '7905008D',
        //     "username"      => '7905008D',
        //     "email"         => '7905008D@gmail.com',
        //     "password"      => bcrypt('7905008D@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);

        // User::create([
        //     "name"          => "WHINY PRIMADASA KAMILUDIN",
        //     "nip"           => '9114263ZY',
        //     "username"      => '9114263ZY',
        //     "email"         => '9114263ZY@gmail.com',
        //     "password"      => bcrypt('9114263ZY@tiger'),
        //     "phone"         => "081249795222",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);
        // User::create([
        //     "name"          => "ADI LAKSONO",
        //     "nip"           => '8504046P3B',
        //     "username"      => '8504046P3B',
        //     "email"         => '8504046P3B@gmail.com',
        //     "password"      => bcrypt('8504046P3B@tiger'),
        //     "phone"         => "08175120567",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);
        // User::create([
        //     "name"          => "DJOKO DWI ATMONO",
        //     "nip"           => '8207216Z',
        //     "username"      => '8207216Z',
        //     "email"         => '8207216Z@gmail.com',
        //     "password"      => bcrypt('8207216Z@tiger'),
        //     "phone"         => "082357536822",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);

        // User::create([
        //     "name"          => "ADE JANUAR SUCIADI",
        //     "nip"           => '8017001TRK',
        //     "username"      => '8017001TRK',
        //     "email"         => '8017001TRK@gmail.com',
        //     "password"      => bcrypt('8017001TRK@tiger'),
        //     "phone"         => "082112019399",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',
        // ]);

        // User::create([
        //     "name"          => "NORMAN SASONO",
        //     "nip"           => '8102012C',
        //     "username"      => '8102012C',
        //     "email"         => '8102012C@gmail.com',
        //     "password"      => bcrypt('8102012C@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "ARIS HERMAWAN",
        //     "nip"           => '8206444Z',
        //     "username"      => '8206444Z',
        //     "email"         => '8206444Z@gmail.com',
        //     "password"      => bcrypt('8206444Z@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "ANDRIAN HADI PRAMONO",
        //     "nip"           => '88111121Z',
        //     "username"      => '88111121Z',
        //     "email"         => '88111121Z@gmail.com',
        //     "password"      => bcrypt('88111121Z@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "BASTIAN RUMPANG",
        //     "nip"           => '7902024F',
        //     "username"      => '7902024F',
        //     "email"         => '7902024F@gmail.com',
        //     "password"      => bcrypt('7902024F@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "PAMUJI IRAWAN",
        //     "nip"           => '86112300Z',
        //     "username"      => '86112300Z',
        //     "email"         => '86112300Z@gmail.com',
        //     "password"      => bcrypt('86112300Z@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "KURNI AWAL",
        //     "nip"           => '8509259Z',
        //     "username"      => '8509259Z',
        //     "email"         => '8509259Z@gmail.com',
        //     "password"      => bcrypt('8509259Z@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "AMRI NUGROHO",
        //     "nip"           => '86112298Z',
        //     "username"      => '86112298Z',
        //     "email"         => '86112298Z@gmail.com',
        //     "password"      => bcrypt('86112298Z@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "KLAIS Y DJODJOBO",
        //     "nip"           => '6994017G',
        //     "username"      => '6994017G',
        //     "email"         => '6994017G@gmail.com',
        //     "password"      => bcrypt('6994017G@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "SLAMET PUJITO",
        //     "nip"           => '7493179D',
        //     "username"      => '7493179D',
        //     "email"         => '7493179D@gmail.com',
        //     "password"      => bcrypt('7493179D@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "AGUS PRASETYO",
        //     "nip"           => '88111606Z',
        //     "username"      => '88111606Z',
        //     "email"         => '88111606Z@gmail.com',
        //     "password"      => bcrypt('88111606Z@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "YUNES INDRAJAYA",
        //     "nip"           => '7907292Z',
        //     "username"      => '7907292Z',
        //     "email"         => '7907292Z@gmail.com',
        //     "password"      => bcrypt('7907292Z@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "AHMAD FAKUL ROHMAN",
        //     "nip"           => '88112016Z',
        //     "username"      => '88112016Z',
        //     "email"         => '88112016Z@gmail.com',
        //     "password"      => bcrypt('88112016Z@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "RIZKI AULIA",
        //     "nip"           => '8611493Z',
        //     "username"      => '8611493Z',
        //     "email"         => '8611493Z@gmail.com',
        //     "password"      => bcrypt('8611493Z@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "HERWIN HIDAYAT",
        //     "nip"           => '7905006R2',
        //     "username"      => '7905006R2',
        //     "email"         => '7905006R2@gmail.com',
        //     "password"      => bcrypt('7905006R2@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "YASSER PUTRA PAMUNGKAS",
        //     "nip"           => '92163198ZY',
        //     "username"      => '92163198ZY',
        //     "email"         => '92163198ZY@gmail.com',
        //     "password"      => bcrypt('92163198ZY@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "HERY AFFANDI",
        //     "nip"           => '7902012A2',
        //     "username"      => '7902012A2',
        //     "email"         => '7902012A2@gmail.com',
        //     "password"      => bcrypt('7902012A2@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "RULITA TRIANDINI",
        //     "nip"           => '8410002TRK',
        //     "username"      => '8410002TRK',
        //     "email"         => '8410002TRK@gmail.com',
        //     "password"      => bcrypt('8410002TRK@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);
        // User::create([
        //     "name"          => "MUHAMMAD IKHSAN",
        //     "nip"           => '92161372ZY',
        //     "username"      => '92161372ZY',
        //     "email"         => '92161372ZY@gmail.com',
        //     "password"      => bcrypt('92161372ZY@tiger'),
        //     "phone"         => "082250021234",
        //     "address"       => "Balikpapan",
        //     "role"          => "user",
        //     "photo"         => NULL,
        //     "birthplace"    => "Jakarta",
        //     "birthdate"     => "1999-10-12",
        //     "gender"        => "L",
        //     "position"      => 'IT',
        //     "kd_region"     => '09',

        // ]);

        User::create([
            "name"          => "SIGIT PRAMUDIA",
            "nip"           => '8609014H2',
            "username"      => '8609014H2',
            "email"         => '8609014H2@gmail.com',
            "password"      => bcrypt('8609014H2@tiger'),
            "phone"         => "082250021234",
            "address"       => "Balikpapan",
            "role"          => "user",
            "photo"         => NULL,
            "birthplace"    => "Jakarta",
            "birthdate"     => "1999-10-12",
            "gender"        => "L",
            "position"      => 'IT',
            "kd_region"     => '09',
        ]);
        User::create([
            "name"          => "GALANG ADI PRAKOSO",
            "nip"           => '9419550ZY',
            "username"      => '9419550ZY',
            "email"         => '9419550ZY@gmail.com',
            "password"      => bcrypt('9419550ZY@tiger'),
            "phone"         => "082250021234",
            "address"       => "Balikpapan",
            "role"          => "user",
            "photo"         => NULL,
            "birthplace"    => "Jakarta",
            "birthdate"     => "1999-10-12",
            "gender"        => "L",
            "position"      => 'IT',
            "kd_region"     => '09',
        ]);
        User::create([
            "name"          => "JAKA HERDIANTO",
            "nip"           => '93172041ZY',
            "username"      => '93172041ZY',
            "email"         => '93172041ZY@gmail.com',
            "password"      => bcrypt('93172041ZY@tiger'),
            "phone"         => "082250021234",
            "address"       => "Balikpapan",
            "role"          => "user",
            "photo"         => NULL,
            "birthplace"    => "Jakarta",
            "birthdate"     => "1999-10-12",
            "gender"        => "L",
            "position"      => 'IT',
            "kd_region"     => '09',
        ]);
        User::create([
            "name"          => "ALBAR MA'RIFAT",
            "nip"           => '9420002ZTY',
            "username"      => '9420002ZTY',
            "email"         => '9420002ZTY@gmail.com',
            "password"      => bcrypt('9420002ZTY@tiger'),
            "phone"         => "082250021234",
            "address"       => "Balikpapan",
            "role"          => "user",
            "photo"         => NULL,
            "birthplace"    => "Jakarta",
            "birthdate"     => "1999-10-12",
            "gender"        => "L",
            "position"      => 'IT',
            "kd_region"     => '09',
        ]);
        User::create([
            "name"          => "MUHAMMAD HASBI ROMADHONI",
            "nip"           => '9015371ZY',
            "username"      => '9015371ZY',
            "email"         => '9015371ZY@gmail.com',
            "password"      => bcrypt('9015371ZY@tiger'),
            "phone"         => "082250021234",
            "address"       => "Balikpapan",
            "role"          => "user",
            "photo"         => NULL,
            "birthplace"    => "Jakarta",
            "birthdate"     => "1999-10-12",
            "gender"        => "L",
            "position"      => 'IT',
            "kd_region"     => '09',
        ]);
        User::create([
            "name"          => "TIRTA ADHI NUGRAHA SE",
            "nip"           => '93163299ZY',
            "username"      => '93163299ZY',
            "email"         => '93163299ZY@gmail.com',
            "password"      => bcrypt('93163299ZY@tiger'),
            "phone"         => "082250021234",
            "address"       => "Balikpapan",
            "role"          => "user",
            "photo"         => NULL,
            "birthplace"    => "Jakarta",
            "birthdate"     => "1999-10-12",
            "gender"        => "L",
            "position"      => 'IT',
            "kd_region"     => '09',
        ]);
        User::create([
            "name"          => "ALVONT MALONDA",
            "nip"           => '9720005ZTY',
            "username"      => '9720005ZTY',
            "email"         => '9720005ZTY@gmail.com',
            "password"      => bcrypt('9720005ZTY@tiger'),
            "phone"         => "082250021234",
            "address"       => "Balikpapan",
            "role"          => "user",
            "photo"         => NULL,
            "birthplace"    => "Jakarta",
            "birthdate"     => "1999-10-12",
            "gender"        => "L",
            "position"      => 'IT',
            "kd_region"     => '09',
        ]);
        User::create([
            "name"          => "ARIETA DWI RAHAYU",
            "nip"           => '9315638ZY',
            "username"      => '9315638ZY',
            "email"         => '9315638ZY@gmail.com',
            "password"      => bcrypt('9315638ZY@tiger'),
            "phone"         => "082250021234",
            "address"       => "Balikpapan",
            "role"          => "user",
            "photo"         => NULL,
            "birthplace"    => "Jakarta",
            "birthdate"     => "1999-10-12",
            "gender"        => "L",
            "position"      => 'IT',
            "kd_region"     => '09',
        ]);
        User::create([
            "name"          => "WAHYU EKA PUTRA",
            "nip"           => '94171804ZY',
            "username"      => '94171804ZY',
            "email"         => '94171804ZY@gmail.com',
            "password"      => bcrypt('94171804ZY@tiger'),
            "phone"         => "082250021234",
            "address"       => "Balikpapan",
            "role"          => "user",
            "photo"         => NULL,
            "birthplace"    => "Jakarta",
            "birthdate"     => "1999-10-12",
            "gender"        => "L",
            "position"      => 'IT',
            "kd_region"     => '09',
        ]);
        User::create([
            "name"          => "Rahmatullah",
            "nip"           => '10221027IT',
            "username"      => '10221027IT',
            "email"         => '10221027IT@gmail.com',
            "password"      => bcrypt('10221027IT@tiger'),
            "phone"         => "082250021234",
            "address"       => "Balikpapan",
            "role"          => "user",
            "photo"         => NULL,
            "birthplace"    => "Jakarta",
            "birthdate"     => "1999-10-12",
            "gender"        => "L",
            "position"      => 'IT',
            "kd_region"     => '09',
        ]);
        User::create([
            "name"          => "Muhammad Syharil Faizal",
            "nip"           => '10221035IT',
            "username"      => '10221035IT',
            "email"         => '10221035IT@gmail.com',
            "password"      => bcrypt('10221035IT@tiger'),
            "phone"         => "082250021234",
            "address"       => "Balikpapan",
            "role"          => "user",
            "photo"         => NULL,
            "birthplace"    => "Jakarta",
            "birthdate"     => "1999-10-12",
            "gender"        => "L",
            "position"      => 'IT',
            "kd_region"     => '09',
        ]);
    }
}
